# Generated by Django 5.1.6 on 2025-02-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('peso_cap_vazia', models.FloatField()),
                ('peso_inicial', models.FloatField()),
                ('peso_final', models.FloatField()),
                ('umidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.amostra')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('descricao', models.TextField(max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('atualizador', models.TextField()),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.analise')),
            ],
        ),
    ]
