# Generated by Django 5.1.6 on 2025-02-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='projeto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='amostra', to='controle.projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analise',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostra', to='controle.amostra'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='controle.analise'),
        ),
    ]
