# Generated by Django 5.1.6 on 2025-02-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_analise_projeto_alter_analise_amostra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='amostra',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='analise',
        ),
        migrations.AlterField(
            model_name='analise',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='atualizador',
            field=models.TextField(blank=True),
        ),
    ]
