# Generated by Django 5.1.6 on 2025-02-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_remove_analise_amostra_remove_projeto_analise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='analise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='controle.analise'),
            preserve_default=False,
        ),
    ]
