# Generated by Django 5.1.6 on 2025-02-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_amostra_analise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amostra',
            old_name='peso_inicial',
            new_name='amostra_inicial',
        ),
    ]
