# Generated by Django 5.1.6 on 2025-02-16 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='atualizador',
        ),
        migrations.AddField(
            model_name='amostra',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amostra',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analise',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analise',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
